### ISSUE TITLE
what does this inception container do ?

### ISSUE THREAD

**Issue by newyangyang** [bitnami/bitnami-docker-tensorflow-inception#3]
Sorry to disturb, this is not actually an issue but a question, so I didn't follow the issue template. 

I followed the readme and everything seems to work fine. But I don't know **What  this container is used for**.
I guess this container do the following thing:
1. read the checkpoint file and produce the model file that is used by the tensorflow serving container.
2. run several test cases, i.e. sending some pictures of cat to the serving container, and see whether the serving container is behaving well. 

If I'm right, how can I see the test result? the `docker logs` did not give much info, just saying : 

>INFO  ==> Starting tensorflow-inception...

And it is a daemon, but what this container is waiting for ? 
Please state the purpose in the readme explicitly and give instructions on how to verify result.

**Comment by tompizmor** [comment]
Hello @newyangyang,

> 1. read the checkpoint file and produce the model file that is used by the tensorflow serving container. 

Exactly. That is basically what it does. Then, after producing the model the container just keep running so you can log into the container and run some queries against the tensorflow-serving container.

In order to see the results, you should follow the steps described [here](https://github.com/bitnami/bitnami-docker-tensorflow-inception#tldr) and then run queries from the inception container. 

This would be an example using [this image](https://www.tensorflow.org/images/grace_hopper.jpg) that is included in the inception container but you are free to mount a volume with your images or log into the container and download them from there.
```
$ docker-compose exec tensorflow-inception inception_client --server=tensorflow-serving:9000 --image=/opt/bitnami/tensorflow-inception/tensorflow/tensorflow/contrib/pi_examples/label_image/data/grace_hopper.jpg
```
